name: Deploy Workflow

on:
  repository_dispatch:
    types:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      WEBHOOK_SECRET: 123456
      
    steps:
      - name: Checkout Repository B
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          if [ "$WEBHOOK_SECRET" != "123456" ]; then
            echo "Webhook secret does not match. Exiting..."
            exit
          fi
          echo "Run repo B"
